# Generated by Django 3.0.2 on 2020-02-24 05:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Communication', 'Communication'), ('Business', 'Business'), ('Civil', 'Civil'), ('Policies', 'Policies'), ('Climate', 'Climate')], max_length=30)),
                ('photo_main', models.ImageField(upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_member', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('banner', 'banner'), ('thumbs', 'thumbs'), ('events', 'events'), ('ads', 'ads'), ('products', 'products')], max_length=30)),
                ('photo_main', models.ImageField(upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='articles/photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_member', models.BooleanField(default=False)),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('diss', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article')),
                ('commentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Author'),
        ),
    ]
