# Generated by Django 3.0.2 on 2020-02-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200224_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
