# Generated by Django 3.0.2 on 2020-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, upload_to='articles/videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('video', 'video'), ('banner', 'banner'), ('thumbs', 'thumbs'), ('events', 'events'), ('ads', 'ads'), ('products', 'products')], max_length=30),
        ),
    ]
