# Generated by Django 3.0.2 on 2020-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_menu',
            field=models.ManyToManyField(to='pages.MenuItem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sub_items',
            field=models.ManyToManyField(to='pages.SubItem'),
        ),
    ]
