# Generated by Django 3.0.2 on 2020-02-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200225_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Menu')),
            ],
        ),
    ]
