# Generated by Django 3.0.2 on 2020-02-19 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('products', models.CharField(max_length=70)),
                ('target_market', models.CharField(choices=[('Local', 'Local'), ('Export', 'Export'), ('LocalnExport', 'LocalnExport')], max_length=30)),
                ('growth_size', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('location', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=30)),
                ('number_employees', models.IntegerField()),
                ('assets_total', models.IntegerField()),
                ('prev_year_closing_balance', models.IntegerField()),
                ('business_size', models.CharField(max_length=70)),
                ('business_logo', models.ImageField(upload_to='staticfiles/business/logo')),
                ('business_site_images', models.ImageField(upload_to='staticfiles/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('funded_amount', models.IntegerField()),
                ('term', models.CharField(max_length=25)),
                ('int_rate', models.CharField(max_length=8)),
                ('installment', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('sub_grade', models.CharField(max_length=2)),
                ('emp_title', models.CharField(default='NA', max_length=40)),
                ('emp_length', models.CharField(max_length=20)),
                ('home_owner', models.CharField(max_length=40)),
                ('annual_inc', models.FloatField()),
                ('verification_status', models.CharField(max_length=40)),
                ('loan_status', models.CharField(max_length=40)),
                ('purpose', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=3)),
                ('dti', models.FloatField()),
                ('open_acc', models.IntegerField()),
                ('revol_bal', models.IntegerField()),
                ('revolv_util', models.CharField(max_length=10)),
                ('total_acct', models.IntegerField()),
                ('application_type', models.CharField(max_length=25)),
                ('total_cur_bal', models.IntegerField()),
                ('acc_open_past_24', models.IntegerField()),
                ('avg_cur_bal', models.IntegerField()),
                ('bc_open_to_buy', models.IntegerField()),
                ('tot_hi_cred', models.IntegerField()),
                ('total_bal_ex_mort', models.IntegerField()),
                ('total_bc_limit', models.IntegerField()),
                ('total_il_high_cred', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='staticfiles/machinery/images')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('current_market_value', models.FloatField()),
                ('supplier', models.CharField(max_length=70)),
                ('manufacturingcompany', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('target_market', models.CharField(choices=[('Local', 'Local'), ('Export', 'Export'), ('LocalnExport', 'LocalnExport')], max_length=30)),
                ('category', models.CharField(choices=[('Industrial', 'Industrial'), ('Consumption', 'Consumption')], max_length=30)),
                ('processe', models.CharField(max_length=70)),
                ('products', models.CharField(max_length=70)),
                ('production_output', models.CharField(max_length=70)),
                ('growth_size', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('location', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=30)),
                ('number_employees', models.IntegerField()),
                ('assets_total', models.IntegerField()),
                ('prev_year_closing_balance', models.IntegerField()),
                ('business_size', models.CharField(max_length=70)),
                ('business_logo', models.ImageField(upload_to='staticfiles/business/logo')),
                ('business_site_images', models.ImageField(upload_to='staticfiles/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_market_avg_price', models.FloatField()),
                ('number_of_markets', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='staticfiles/products/images')),
                ('short_name', models.CharField(max_length=70)),
                ('long_name', models.CharField(max_length=270)),
                ('shortDescrip', models.CharField(max_length=270)),
                ('brandcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmanager.BrandCompany')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmanager.FoodGroup')),
                ('manufacturingcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmanager.ManufacturingCompany')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='staticfiles/rawmaterials/images')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('current_market_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('composition', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmanager.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Proces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('machines_used', models.TextField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmanager.Machinery')),
                ('rawmaterials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmanager.RawMaterials')),
            ],
        ),
    ]
