bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

countries_choices = {
'Algeria':'Algeria',
'Angola':'Angola',
'Benin':'Benin',
'Botswana':'Botswana',
'Burkina_Faso':'Burkina_Faso',
'Burundi':'Burundi',
'Cameroon':'Cameroon',
'Cape_Verde':'Cape-Verde',
'Central_African_Republic':'Central-African-Republic',
'Chad':'Chad',
'Camoros':'Camoros',
'DRC':'Democratic-Republic-of-the-Congo',
'Djibouti':'Djibouti',
'Egypt':'Egypt',
'Equatorial-Guinea':'Equatorial-Guinea',
'Eritrea':'Eritrea',
'Ethiopia':'Ethiopia',
'Gabon':'Gabon',
'Gambia':'Gambia',
'Ghana':'Ghana',
'Guinea':'Guinea',
'Guinea-Bissau':'Guinea-Bissau',
'Ivory_Coast':'Ivory-Coast',
'Kenya':'Kenya',
'Lesotho':'Lesotho',
'Liberia':'Liberia',
'Libya':'Libya',
'Madagascar':'Madagascar',
'Malawi':'Malawi',
'Mali':'Mali',
'Mauritania':'Mauritania',
'Mauritius':'Mauritius',
'Morocco':'Morocco',
'Mozambique':'Mozambique',
'Namibia':'Namibia',
'Niger':'Niger',
'Nigeria':'Nigeria',
'Rwanda':'Rwanda',
'Sao_Tome_and_Principe':'Sao-Tome-and-Principe',
'Senegal':'Senegal',
'Seychelles':'Seychelles',
'Sierra_Leone':'Sierra-Leone',
'Somalia':'Somalia',
'South_Africa':'South-Africa',
'South_Sudan':'South-Sudan',
'Sudan':'Sudan',
'Swaziland':'Swaziland',
'Tanzania':'Tanzania',
'Togo':'Togo',
'Tunisia':'Tunisia',
'Uganda':'Uganda',
'Zambia':'Zambia',
'Zimbabwe':'Zimbabwe',
}
role_choices = {
'president':'president',
'secretary':'secretary',

}
price_choices={
 '100000':'$100,000',
  '200000':'$200,000',
  '300000':'$300,000',
  '400000':'$400,000',
  '500000':'$500,000',
  '600000':'$600,000',
  '700000':'$700,000',
  '800000':'$800,000',
  '900000':'$900,000',
  '1000000':'$1M+',
}

state_choices = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}