# Generated by Django 3.0.2 on 2020-02-19 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProduce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=70)),
                ('long_name', models.CharField(max_length=270)),
                ('shortDescrip', models.CharField(max_length=270)),
                ('current_market_avg_price', models.FloatField(default=0)),
                ('number_of_markets', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='staticfiles/products/images')),
                ('category', models.CharField(choices=[('Industrial', 'Industrial'), ('Consumption', 'Consumption')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('target_market', models.CharField(choices=[('Local', 'Local'), ('Export', 'Export'), ('LocalnExport', 'LocalnExport')], max_length=30)),
                ('category', models.CharField(choices=[('Industrial', 'Industrial'), ('Consumption', 'Consumption')], max_length=30)),
                ('processes', models.TextField()),
                ('production_output', models.CharField(max_length=70)),
                ('growth_size', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('location', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=30)),
                ('number_employees', models.IntegerField()),
                ('assets_total', models.IntegerField()),
                ('prev_year_closing_balance', models.IntegerField()),
                ('business_size', models.CharField(max_length=70)),
                ('business_logo', models.ImageField(upload_to='staticfiles/business/logo')),
                ('business_site_images', models.ImageField(upload_to='staticfiles/images')),
                ('farm_produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farm.FarmProduce')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
